apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "collab.fullname" . }}-mariadb
  labels:
    app.kubernetes.io/name: {{ include "collab.name" . }}-mariadb
    helm.sh/chart: {{ include "collab.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "collab.name" . }}-mariadb
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "collab.name" . }}-mariadb
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-mariadb
          image: "{{ .Values.mariadb.image.repository }}:{{ .Values.mariadb.image.tag }}"
          imagePullPolicy: {{ .Values.mariadb.image.pullPolicy }}
          ports:
          - name: mariadb
            containerPort: 3306
            protocol: TCP
          env:
          - name: "MYSQL_ROOT_PASSWORD"
            valueFrom:
              secretKeyRef:
                name: {{ template "collab.fullname" . }}-env
                key: db-root
          - name: "MYSQL_DATABASE"
            value: "collab"
          - name: "MYSQL_USER"
            valueFrom:
              secretKeyRef:
                name: {{ template "collab.fullname" . }}-env
                key: db-user
          - name: "MYSQL_PASSWORD"
            valueFrom:
              secretKeyRef:
                name: {{ template "collab.fullname" . }}-env
                key: db-password
          resources:
{{ toYaml .Values.mariadb.resources | indent 12 }}
    {{- with .Values.mariadb.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.mariadb.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.mariadb.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
